export enum ClientAction {
  INSERT = 'insert',
  FIND = 'find',
  UPDATE = 'update',
  REMOVE = 'remove',
  COUNT = 'count',
  START_TRANSACTION = 'startTransaction',
  COMMIT_TRANSACTION = 'commitTransaction',
  ROLLBACK_TRANSACTION = 'rollbackTransaction',
  MIGRATE_UP = 'migrateUp',
  MIGRATE_DOWN = 'migrateDown',
  GET_MIGRATIONS = 'getMigration',
  ADD_COLLECTION = 'addCollection',
  REMOVE_COLLECTION = 'removeCollection',
  UPDATE_COLLECTION = 'updateCollection',
  GET_COLLECTION_NAMES = 'getCollectionNames',
  GET_COLLECTION_SCHEMA = 'getCollectionSchema',
  GET_DATABASE_NAMES = 'getDatabaseNames',
}
