export const DEFAULT_CONNECTION_PULL_SIZE = 5;
export const DEFAULT_CONNECT_TIMEOUT_VALUE = 30000;
export const DEFAULT_RECONNECT_TIMEOUT_VALUE = 1000;
export const DEFAULT_REQUEST_TIMEOUT_VALUE = 30000;
export const DEFAULT_SERVER_PORT = 34567;
