export enum Types {
  OBJECT_ID = 'OBJECT_ID',
  BOOLEAN = 'BOOLEAN',
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  TIME = 'TIME',
  REFERENCE = 'REFERENCE',
  POSITION = 'POSITION',
  ARRAY = 'ARRAY',
}
